name: Create and Setup Repository

on:
  push:
    branches:
      - main

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Read JSON file
      id: read-json
      run: |
        echo "::set-output name=repo_name::$(jq -r '.repo_name' repo-details.json)"
        echo "::set-output name=source_repo::$(jq -r '.source_repo' repo-details.json)"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Create new repository
      run: |
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
             -d '{"name":"${{ steps.read-json.outputs.repo_name }}"}' \
             https://api.github.com/user/repos

    - name: Pull code from source repository
      run: git clone ${{ steps.read-json.outputs.source_repo }} temp-repo
    
    - name: change to the cloned repo
      run: cd temp-repo
    
    # - name: Configure Git
    #   run: |
    #     git config user.name "github-actions[bot]"
    #     git config user.email "github-actions[bot]@users.noreply.github.com"
    
    # - name: Push changes
    #   run: |
    #     git remote set-url origin https://SVenkataSivaSatish:${{ secrets.GH_TOKEN }}@github.com/SVenkataSivaSatish/app-repo1.git
    #     git push origin main 
    
    - name: push the contents to the app-repo 
      run: |
        git remote set-url origin https://github.com/${{ github.repository_owner }}/${{ steps.read-json.outputs.repo_name }}.git
        git push -u origin main
